# Personal Expense Audit

This notebook uses Python and Pandas to review a personal expense dataset.

## Objectives
- Inspect the records, columns, and data types
- Check for missing and duplicate records
- Review transaction amounts and identify the largest expenses
- Standardize category names
- Compare category totals, transaction counts, and average amounts
- Examine spending by day and month
- Summarize total expenditure and average transaction amount

In [1]:
import pandas as pd

## 1. Load the Dataset

The expense data is stored in a CSV file. We will load it into a Pandas DataFrame for analysis.

In [2]:
df = pd.read_csv("personal_expense_audit.csv")

### Initial Data Inspection

First, we display the complete dataset to get an initial understanding of the available records.

In [3]:
df

          Date        Category  Description  Amount
0   2026-01-02            Food    Groceries    1250
1   2026-01-04            food    Groceries     840
2   2026-01-06       Transport        Metro     320
3   2026-01-08   Entertainment        Movie     650
4   2026-01-10           Food    Restaurant     780
5   2026-01-13        Shopping      Clothes    1450
6   2026-01-16       transport         Fuel    1100
7   2026-01-19           Bills     Internet     699
8   2026-01-22            Food    Groceries     920
9   2026-01-25   Entertainment        Games     499
10  2026-01-28        Shopping  Accessories     850
11  2026-02-01            food    Groceries    1380
12  2026-02-03      Transport         Metro     360
13  2026-02-05           Bills       Mobile     499
14  2026-02-08            Food   Restaurant     920
15  2026-02-11        shopping      Clothes    1200
16  2026-02-14   Entertainment        Movie     720
17  2026-02-17       Transport         Fuel    1250
18  2026-02-20           Food     Groceries     760
19  2026-02-23          Bills   Electricity    1180
20  2026-02-26        Shopping  Accessories     640
21  2026-03-02            Food    Groceries    1120
22  2026-03-05       transport        Metro     410
23  2026-03-07  Entertainment         Movie     550
24  2026-03-10            food   Restaurant     850
25  2026-03-13        Shopping      Clothes    1750
26  2026-03-16       Transport         Fuel    1320
27  2026-03-19           Bills     Internet     699
28  2026-03-22            Food    Groceries     980
29  2026-03-25   Entertainment        Games     799
30  2026-03-28       Shopping   Accessories     920
31  2026-04-01           Food     Groceries    1290
32  2026-04-04       Transport        Metro     380
33  2026-04-06           Bills       Mobile     499
34  2026-04-09            food   Restaurant    1050
35  2026-04-12        Shopping      Clothes    2100
36  2026-04-15   Entertainment        Movie     680
37  2026-04-18      transport          Fuel    1180
38  2026-04-21            Food    Groceries     870
39  2026-04-24          Bills   Electricity    1350
40  2026-04-27        Shopping  Accessories     760

### Dataset Structure

We use `info()` to examine the number of entries, column names, data types, and non-null values.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         41 non-null     str
 1   Category     41 non-null     str
 2   Description  41 non-null     str
 3   Amount       41 non-null     int64
dtypes: int64(1), str(3)
memory usage: 1.4 KB

### Statistical Summary

The `describe()` method provides summary statistics for the numerical columns in the dataset.

In [5]:
df.describe()

            Amount
count    41.000000
mean    922.536585
std     384.846794
min     320.000000
25%     680.000000
50%     850.000000
75%    1180.000000
max    2100.000000

### Missing Value Check

We check each column for missing values to determine whether the dataset requires any missing-data treatment.

In [6]:
df.isna().sum()

Date           0
Category       0
Description    0
Amount         0
dtype: int64

### Duplicate Record Check

Count exact duplicate rows for review. Identical transactions can be legitimate, so check them before deciding whether to remove any.

In [7]:
df.duplicated().sum()

np.int64(0)

### Viewing the Dataset

We inspect the first and last few records to verify the structure and contents of the dataset.

In [8]:
df.head()

         Date       Category Description  Amount
0  2026-01-02           Food   Groceries    1250
1  2026-01-04           food   Groceries     840
2  2026-01-06      Transport       Metro     320
3  2026-01-08  Entertainment       Movie     650
4  2026-01-10          Food   Restaurant     780

In [9]:
df.tail()

          Date       Category  Description  Amount
36  2026-04-15  Entertainment        Movie     680
37  2026-04-18     transport          Fuel    1180
38  2026-04-21           Food    Groceries     870
39  2026-04-24         Bills   Electricity    1350
40  2026-04-27       Shopping  Accessories     760

## 2. Expense Analysis

Review transaction amounts and identify the largest expense.

### Identifying the Largest Transaction

We identify the transaction with the highest expense amount and display its complete details.

In [10]:
df[df['Amount'] == df['Amount'].max()][['Date', 'Category', 'Description','Amount']]

          Date  Category Description  Amount
35  2026-04-12  Shopping     Clothes    2100

## 3. Category Cleaning

Before analyzing spending by category, we first examine the existing category values for inconsistencies such as different capitalization or unnecessary spaces.

### Inspecting Category Values

Check the unique category values for differences in capitalization and leading or trailing spaces before standardizing them.

In [11]:
df['Category'].unique()

<StringArray>
[          'Food',           'food',      'Transport',  'Entertainment',
          'Food ',       'Shopping',      'transport',          'Bills',
     'Transport ',       'shopping',         'Bills ', 'Entertainment ',
      'Shopping ',     'transport ']
Length: 14, dtype: str

### Standardizing Category Names

The category values contain inconsistent formatting. We standardize them by removing unnecessary spaces and using consistent capitalization.

In [12]:
df['Category'] = df['Category'].str.capitalize().str.strip()

### Verify the Cleaning

We check the unique category values again to confirm that the categories have been standardized successfully.

In [13]:
df['Category'].unique()

<StringArray>
['Food', 'Transport', 'Entertainment', 'Shopping', 'Bills']
Length: 5, dtype: str

## 4. Category Analysis

We first count the number of transactions belonging to each expense category.

In [14]:
df['Category'].value_counts()

Category
Food             13
Transport         8
Shopping          8
Entertainment     6
Bills             6
Name: count, dtype: int64

### Total Spending by Category

We calculate the total amount spent in each category using `groupby()` and `sum()`.

In [15]:
category_totals = df.groupby("Category")["Amount"].sum()
category_totals.sort_values(ascending= False)

Category
Food             13010
Shopping          9670
Transport         6320
Bills             4926
Entertainment     3898
Name: Amount, dtype: int64

### Highest-Spending Category

The totals above compare expenditure across categories. This cell returns the category with the greatest total spending.

In [16]:
category_totals.idxmax()

'Food'

### Average Transaction Amount by Category

Compare the average transaction amount within each category. A category’s average can differ from its total because categories contain different numbers of transactions.

In [17]:
df.groupby("Category")["Amount"].mean()

Category
Bills             821.000000
Entertainment     649.666667
Food             1000.769231
Shopping         1208.750000
Transport         790.000000
Name: Amount, dtype: float64

## 5. Spending Over Time

Convert transaction dates to datetime values so spending can be grouped by day and month.

In [18]:
df['Date'] = pd.to_datetime(df['Date'])

### Daily Spending

Group transactions by date to calculate the total amount spent on each day.

In [19]:
daily_spending = df.groupby('Date')['Amount'].sum()

In [20]:
daily_spending

Date
2026-01-02    1250
2026-01-04     840
2026-01-06     320
2026-01-08     650
2026-01-10     780
2026-01-13    1450
2026-01-16    1100
2026-01-19     699
2026-01-22     920
2026-01-25     499
2026-01-28     850
2026-02-01    1380
2026-02-03     360
2026-02-05     499
2026-02-08     920
2026-02-11    1200
2026-02-14     720
2026-02-17    1250
2026-02-20     760
2026-02-23    1180
2026-02-26     640
2026-03-02    1120
2026-03-05     410
2026-03-07     550
2026-03-10     850
2026-03-13    1750
2026-03-16    1320
2026-03-19     699
2026-03-22     980
2026-03-25     799
2026-03-28     920
2026-04-01    1290
2026-04-04     380
2026-04-06     499
2026-04-09    1050
2026-04-12    2100
2026-04-15     680
2026-04-18    1180
2026-04-21     870
2026-04-24    1350
2026-04-27     760
Name: Amount, dtype: int64

### Highest-Spending Day

Identify the date with the largest daily total and the amount spent that day.

In [21]:
daily_spending.idxmax()

Timestamp('2026-04-12 00:00:00')

In [22]:
daily_spending.max()

np.int64(2100)

### Monthly Spending

Sum transaction amounts by calendar month. The current dataset covers 2026, so grouping by month number is sufficient here.

In [23]:
df.groupby(df['Date'].dt.month)['Amount'].sum()

Date
1     9358
2     8909
3     9398
4    10159
Name: Amount, dtype: int64

### Top Three Categories by Total Spending

Rank categories by total expenditure and display the three highest.

In [24]:
df.groupby("Category")["Amount"].sum().sort_values(ascending=False).head(3)

Category
Food         13010
Shopping      9670
Transport     6320
Name: Amount, dtype: int64

## 6. Overall Summary

Summarize total expenditure and the average transaction amount for the full dataset.

In [25]:
print("Total Expenditure:", df["Amount"].sum())
print("Average Transaction:", df["Amount"].mean())

Total Expenditure: 37824
Average Transaction: 922.5365853658536

## Key Findings

- The dataset contains 41 transactions and has no missing values.
- Total expenditure is 37,824, with an average transaction amount of about 922.54.
- Food has the largest category total at 13,010 and the highest transaction count, with 13 transactions.
- The largest single transaction is 2,100 for Clothes on 12 April 2026.
- April has the highest monthly total at 10,159.