In [87]:
import pandas as pd

In [88]:
df = pd.read_csv("personal_expense_audit.csv")

In [89]:
df

          Date        Category  Description  Amount
0   2026-01-02            Food    Groceries    1250
1   2026-01-04            food    Groceries     840
2   2026-01-06       Transport        Metro     320
3   2026-01-08   Entertainment        Movie     650
4   2026-01-10           Food    Restaurant     780
5   2026-01-13        Shopping      Clothes    1450
6   2026-01-16       transport         Fuel    1100
7   2026-01-19           Bills     Internet     699
8   2026-01-22            Food    Groceries     920
9   2026-01-25   Entertainment        Games     499
10  2026-01-28        Shopping  Accessories     850
11  2026-02-01            food    Groceries    1380
12  2026-02-03      Transport         Metro     360
13  2026-02-05           Bills       Mobile     499
14  2026-02-08            Food   Restaurant     920
15  2026-02-11        shopping      Clothes    1200
16  2026-02-14   Entertainment        Movie     720
17  2026-02-17       Transport         Fuel    1250
18  2026-02-20           Food     Groceries     760
19  2026-02-23          Bills   Electricity    1180
20  2026-02-26        Shopping  Accessories     640
21  2026-03-02            Food    Groceries    1120
22  2026-03-05       transport        Metro     410
23  2026-03-07  Entertainment         Movie     550
24  2026-03-10            food   Restaurant     850
25  2026-03-13        Shopping      Clothes    1750
26  2026-03-16       Transport         Fuel    1320
27  2026-03-19           Bills     Internet     699
28  2026-03-22            Food    Groceries     980
29  2026-03-25   Entertainment        Games     799
30  2026-03-28       Shopping   Accessories     920
31  2026-04-01           Food     Groceries    1290
32  2026-04-04       Transport        Metro     380
33  2026-04-06           Bills       Mobile     499
34  2026-04-09            food   Restaurant    1050
35  2026-04-12        Shopping      Clothes    2100
36  2026-04-15   Entertainment        Movie     680
37  2026-04-18      transport          Fuel    1180
38  2026-04-21            Food    Groceries     870
39  2026-04-24          Bills   Electricity    1350
40  2026-04-27        Shopping  Accessories     760

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         41 non-null     str
 1   Category     41 non-null     str
 2   Description  41 non-null     str
 3   Amount       41 non-null     int64
dtypes: int64(1), str(3)
memory usage: 1.4 KB

In [91]:
df.describe()

            Amount
count    41.000000
mean    922.536585
std     384.846794
min     320.000000
25%     680.000000
50%     850.000000
75%    1180.000000
max    2100.000000

In [92]:
df.isna().sum()

Date           0
Category       0
Description    0
Amount         0
dtype: int64

In [93]:
df.head()

         Date       Category Description  Amount
0  2026-01-02           Food   Groceries    1250
1  2026-01-04           food   Groceries     840
2  2026-01-06      Transport       Metro     320
3  2026-01-08  Entertainment       Movie     650
4  2026-01-10          Food   Restaurant     780

In [94]:
df.tail()

          Date       Category  Description  Amount
36  2026-04-15  Entertainment        Movie     680
37  2026-04-18     transport          Fuel    1180
38  2026-04-21           Food    Groceries     870
39  2026-04-24         Bills   Electricity    1350
40  2026-04-27       Shopping  Accessories     760

In [95]:
df['Amount'].describe()

count      41.000000
mean      922.536585
std       384.846794
min       320.000000
25%       680.000000
50%       850.000000
75%      1180.000000
max      2100.000000
Name: Amount, dtype: float64

In [96]:
df[df['Amount'] == df['Amount'].max()][['Date', 'Category', 'Description','Amount']]

          Date  Category Description  Amount
35  2026-04-12  Shopping     Clothes    2100

In [97]:
df['Category'].unique()

<StringArray>
[          'Food',           'food',      'Transport',  'Entertainment',
          'Food ',       'Shopping',      'transport',          'Bills',
     'Transport ',       'shopping',         'Bills ', 'Entertainment ',
      'Shopping ',     'transport ']
Length: 14, dtype: str

In [98]:
df['Category'] = df['Category'].str.capitalize().str.strip()

In [99]:
df

          Date       Category  Description  Amount
0   2026-01-02           Food    Groceries    1250
1   2026-01-04           Food    Groceries     840
2   2026-01-06      Transport        Metro     320
3   2026-01-08  Entertainment        Movie     650
4   2026-01-10           Food   Restaurant     780
5   2026-01-13       Shopping      Clothes    1450
6   2026-01-16      Transport         Fuel    1100
7   2026-01-19          Bills     Internet     699
8   2026-01-22           Food    Groceries     920
9   2026-01-25  Entertainment        Games     499
10  2026-01-28       Shopping  Accessories     850
11  2026-02-01           Food    Groceries    1380
12  2026-02-03      Transport        Metro     360
13  2026-02-05          Bills       Mobile     499
14  2026-02-08           Food   Restaurant     920
15  2026-02-11       Shopping      Clothes    1200
16  2026-02-14  Entertainment        Movie     720
17  2026-02-17      Transport         Fuel    1250
18  2026-02-20           Food    Groceries     760
19  2026-02-23          Bills  Electricity    1180
20  2026-02-26       Shopping  Accessories     640
21  2026-03-02           Food    Groceries    1120
22  2026-03-05      Transport        Metro     410
23  2026-03-07  Entertainment        Movie     550
24  2026-03-10           Food   Restaurant     850
25  2026-03-13       Shopping      Clothes    1750
26  2026-03-16      Transport         Fuel    1320
27  2026-03-19          Bills     Internet     699
28  2026-03-22           Food    Groceries     980
29  2026-03-25  Entertainment        Games     799
30  2026-03-28       Shopping  Accessories     920
31  2026-04-01           Food    Groceries    1290
32  2026-04-04      Transport        Metro     380
33  2026-04-06          Bills       Mobile     499
34  2026-04-09           Food   Restaurant    1050
35  2026-04-12       Shopping      Clothes    2100
36  2026-04-15  Entertainment        Movie     680
37  2026-04-18      Transport         Fuel    1180
38  2026-04-21           Food    Groceries     870
39  2026-04-24          Bills  Electricity    1350
40  2026-04-27       Shopping  Accessories     760

In [100]:
df['Category'].unique()

<StringArray>
['Food', 'Transport', 'Entertainment', 'Shopping', 'Bills']
Length: 5, dtype: str

In [101]:
df['Category'].value_counts()

Category
Food             13
Transport         8
Shopping          8
Entertainment     6
Bills             6
Name: count, dtype: int64

In [106]:
df.groupby(df['Category'])['Amount'].sum()

Category
Bills             4926
Entertainment     3898
Food             13010
Shopping          9670
Transport         6320
Name: Amount, dtype: int64